export default [
  "GB",
  "England",
  "Scotland",
  "Wales",
  "London",
  "South England",
  "South West England",
  "South East England",
  "East Midlands",
  "West Midlands",
  "South Wales",
  "North Wales & Merseyside",
  "North East England",
  "North West England",
  "East England",
  "Yorkshire",
  "South Scotland",
  "North Scotland",
];
